import About from "../screens/About";
import Chat from "../screens/Chat";
import Gst from "../screens/Gst";
import HelpSupport from "../screens/HelpSupport";
import HowToPlay from "../screens/HowToPlay";
import Legality from "../screens/Legality";
import PaymentScreen from "../screens/PaymentScreen";
import ResponsiblePlay from "../screens/ResponsiblePlay";
import ShareContests from "../screens/ShareContests";
import Tds from "../screens/Tds";
import TermsAndConditions from "../screens/TermOfServices";

export const NavigationString = {
  Splash: 'Splash',
  Login: 'Login',
  VerifyOTP: 'VerifyOTP',
  Home: 'Home',
  HomeContestList: 'HomeContestList',
  MyMatches: 'MyMatches',
  ReferEarn: 'ReferEarn',
  Profile: 'Profile',
  TabBar: 'TabBar',
  Cricket: 'Cricket',
  Kabaddi: 'Kabaddi',
  Football: 'Football',
  BasketBall: 'BasketBall',
  TopTabBar: 'TopTabBar',
  BottomTabBar: 'BottomTabBar',
  Setting: 'Setting',
  DrawerBar: 'DrawerBar',
  BonusCash: 'BonusCash',
  MyWallet: 'MyWallet',
  PrivateContest: 'PrivateContest',
  CreatePrivateContest: 'CreatePrivateContest',
  JoinPrivateContest: 'JoinPrivateContest',
  PrivateContestParticipate: 'PrivateContestParticipate',
  ContestList: 'ContestList',
  ViewContest: 'ViewContest',
  BookBids: 'BookBids',
  BiddersList: 'BiddersList',
  YourBids: 'YourBids',
  MyAccount: 'MyAccount',
  AccountOverView: 'AccountOverView',
  Winners: 'Winners',
  AllWinners: 'AllWinners',
  AddAddressDetails: 'AddAddressDetails',
  ChangeUserName: 'ChangeUserName',
  AddEmailAddress: 'AddEmailAddress',
  KYCVerification: 'KYCVerification',
  CashWithdraw: 'CashWithdraw',
  ViewTransaction: 'ViewTransaction',
  BonusSummary: 'BonusSummary',
  PrivateContestTransactions: 'PrivateContestTransactions',
  WithdrawalHistory: 'WithdrawalHistory',
  AddCash: 'AddCash',
  VipExclusiveOffer: 'VipExclusiveOffer',
  TransactionSuccessful: 'TransactionSuccessful',
  PrivacySettings: 'PrivacySettings',
  BankVerification: 'BankVerification',
  PrivateContestList: 'PrivateContestList',
  PrivateViewContest: 'PrivateViewContest',
  ViewHomeContest: 'ViewHomeContest',
  BookHomeBids: 'BookHomeBids',
  BookPrivateBids: 'BookPrivateBids',
  BiddersHomeList: 'BiddersHomeList',
  YourBidsHome: 'YourBidsHome',
  MyContestList: 'MyContestList',
  ContactUserProfile: 'ContactUserProfile',
  Notification: 'Notification',
  UpdateProfile: 'UpdateProfile',
  PdfView: 'PdfView',
  UserRefer: 'UserRefer',
  PrivacyPolicy: "PrivacyPolicy",
  TermsAndConditions: "TermsAndConditions",
  Legality: "Legality",
  About: "About",
  HelpSupport: "HelpSupport",
  Chat: "Chat",
  HowToPlay: "HowToPlay",
  ResponsiblePlay: "ResponsiblePlay",
  Tds: "Tds",
  Gst: "Gst",
  SucessScreen: "SucessScreen",
  ShareContests: "ShareContests",
  CashFreeWebView: "CashFreeWebView",
  PaymentScreen: "PaymentScreen"
};  